#!/usr/bin/env bash
# In-container: generate the HypXRland session launch config (the preview-xr.sh
# model, adapted for the container). Emits:
#   source = <base>          the omarchy-seeded ~/.config/hypr/hyprland.conf, or a
#                            user conf the wrapper bind-mounted via --conf
#   monitor = , preferred…   neutralizes any host-specific monitor layout from the
#                            base config (the container nests into ONE wayland
#                            output; the omarchy monitors.conf pins scale 2 / auto)
#   openxr { … }             enabled + gpu pin + optional overlay/passthrough
#   xrmonitor = …            the two default XR monitors (mirrors preview-xr.conf)
#
# Env inputs:
#   XR_BASE_CONF    base config to source (default ~/.config/hypr/hyprland.conf)
#   XR_GPU_NODE     render node for openxr:gpu (e.g. /dev/dri/renderD129)
#   XR_OVERLAY      1 -> openxr:overlay = 1 (XR_EXTX_overlay; the --env hook, unused
#                   in WP3 but wired so a later ambient-background mode is a one-liner)
#   XR_PASSTHROUGH  1 -> openxr:blend_mode = alpha (composite over passthrough)
#
# Usage: merge-conf.sh <output-file>   (writes the config there; echoes the path)
set -euo pipefail

OUT="${1:?usage: merge-conf.sh <output-file>}"
BASE="${XR_BASE_CONF:-$HOME/.config/hypr/hyprland.conf}"
[[ -f $BASE ]] || { echo "merge-conf: base config not found: $BASE" >&2; exit 1; }

{
    echo "# Generated by containers/session/merge-conf.sh — do not edit by hand."
    echo "# Base session config (full Omarchy desktop, or a --conf override):"
    echo "source = $BASE"
    echo ""
    echo "# The container nests into ONE wayland output; neutralize any host monitor"
    echo "# layout from the base (omarchy monitors.conf pins scale 2 / auto-auto)."
    echo "monitor = , preferred, auto, 1"
    echo ""
    echo "openxr {"
    echo "    enabled = 1"
    [[ -n ${XR_GPU_NODE:-} ]]      && echo "    gpu = $XR_GPU_NODE"
    [[ ${XR_OVERLAY:-0} == 1 ]]    && echo "    overlay = 1"
    [[ ${XR_PASSTHROUGH:-0} == 1 ]] && echo "    blend_mode = alpha"
    echo "}"
    echo ""
    echo "# Two default XR monitors (mirrors scripts/preview-xr.conf):"
    echo "#   world-locked panel straight ahead at eye height,"
    echo "xrmonitor = XR-main, 1920x1080@60, anchor:local pos:0,1.5,-1.5 yaw:0, size:1.6"
    echo "#   and a head-leashed side panel that springs to follow your view."
    echo "xrmonitor = XR-side, 1280x720@60, anchor:head offset:0.9,0,-1.2, size:0.9"
} > "$OUT"

echo "$OUT"
