#!/usr/bin/env bash
# Generate a nested-session Hyprland config that mirrors the user's Omarchy
# desktop (keybinds, look'n'feel, theme) but is SAFE to run as a NESTED dev
# compositor for the HypXRland preview (scripts/preview-xr.sh --conf ...).
#
# What this produces (under ~/.config/hypr/xr-nested/):
#   nested.conf   - the generated config: sources the WANTED Omarchy/user files,
#                   skips anything that mutates global session state or launches
#                   service-like daemons, adds a PATH shim + XR essentials.
#   bin/uwsm-app  - a shim that execs its command directly instead of routing
#                   through the host's wayland-wm-app-daemon / systemd session
#                   (so keybind-launched apps land in the NESTED session).
#
# Re-run this whenever your Omarchy config changes to keep nested.conf in sync
# (it SOURCES the live files, so most edits need no regeneration; regenerate
# only to pick up structural changes or a new $PATH).
#
# Machine-agnostic: derives $HOME / $PATH at runtime, writes no hardcoded paths
# for other machines. The generated file lives in your home and is specific to
# this machine by design.

set -euo pipefail

HOME_DIR="${HOME:?HOME must be set}"
OUT_DIR="$HOME_DIR/.config/hypr/xr-nested"
SHIM_DIR="$OUT_DIR/bin"
NESTED_CONF="$OUT_DIR/nested.conf"

OMARCHY_DEFAULT="$HOME_DIR/.local/share/omarchy/default/hypr"
USER_HYPR="$HOME_DIR/.config/hypr"
THEME_DIR="$HOME_DIR/.config/omarchy/current/theme"

mkdir -p "$SHIM_DIR"

# --------------------------------------------------------------------------
# 1. uwsm-app shim
# --------------------------------------------------------------------------
# Omarchy keybinds launch apps via `uwsm-app -- <cmd>` (and `setsid uwsm-app --
# <cmd>` from omarchy-launch-* scripts). The real uwsm-app hands the command to
# the HOST's wayland-wm-app-daemon.service + systemd user session, so the app is
# spawned by the HOST session (wrong WAYLAND_DISPLAY, host env) instead of the
# nested compositor. This shim just execs the command directly: apps then
# inherit the nested compositor's WAYLAND_DISPLAY and land in the nested session.
cat > "$SHIM_DIR/uwsm-app" <<'SHIM'
#!/bin/sh
# Nested-session uwsm-app shim (generated by gen-omarchy-xr-conf.sh).
# Real uwsm-app routes through the host wayland-wm-app-daemon + systemd session;
# here we exec the target command directly so it inherits the nested compositor's
# WAYLAND_DISPLAY. Handles the Omarchy call forms:
#   uwsm-app -- CMD ARGS
#   uwsm-app -t service -- CMD          (any uwsm 'app' options before --)
#   setsid uwsm-app -- CMD              (setsid execs us; nothing special)
#   uwsm-app -- env VAR=x CMD ...       (env is a real binary, exec'd normally)
# Strategy: drop everything up to and including the first "--", exec the rest.
# Daemon-control pseudo-args are no-oped so nothing tries to poke the host daemon.

case "${1:-}" in
    ping) echo pong; exit 0 ;;
    stop) exit 0 ;;
esac

# Is there a "--" separator? (Omarchy always uses one.)
has_sep=0
for a in "$@"; do
    [ "$a" = "--" ] && { has_sep=1; break; }
done

if [ "$has_sep" = 1 ]; then
    while [ "$#" -gt 0 ]; do
        arg="$1"; shift
        [ "$arg" = "--" ] && break
    done
fi

[ "$#" -eq 0 ] && { echo "uwsm-app shim: nothing to exec" >&2; exit 1; }
exec "$@"
SHIM
chmod +x "$SHIM_DIR/uwsm-app"

# --------------------------------------------------------------------------
# NOTE on DBus single-instance apps (no override needed anymore)
# --------------------------------------------------------------------------
# preview-xr.sh launches the nested Hyprland under `dbus-run-session`, so the
# nested session has its OWN private DBus session bus. GApplication/DBus
# single-instance apps (ghostty, walker, mako, the browser, nautilus, obsidian…)
# therefore find NO existing instance on this fresh bus and start a NEW one inside
# the nested session — no more delegating to the HOST instance. That means the old
# per-terminal `--gtk-single-instance=false` override is unnecessary: the stock
# `uwsm-app -- xdg-terminal-exec` bind (via the shim above) already lands nested.
# --------------------------------------------------------------------------
# 2. nested.conf
# --------------------------------------------------------------------------
# Prepend the shim dir to the PATH captured now. hyprlang does NOT expand shell
# env vars ($PATH) inside `env =` values (only its own $config-vars), so we bake
# the full literal PATH here. The nested compositor setenv()s this and every
# keybind-launched app inherits the shim-first PATH.
PATH_LITERAL="$SHIM_DIR:$PATH"

cat > "$NESTED_CONF" <<CONF
# ==========================================================================
# Omarchy-mirror nested config for the HypXRland preview.
# GENERATED by scripts/gen-omarchy-xr-conf.sh — do not edit by hand; re-run it.
#
# Launch with:  scripts/preview-xr.sh --conf $NESTED_CONF
#
# Mirrors the user's Omarchy desktop (keybinds / look'n'feel / theme) while
# excluding everything that mutates global session state or starts daemons:
#   EXCLUDED  default/hypr/autostart.conf   (hypridle, waybar, fcitx5, swaybg,
#                                             polkit, monitor-watch, mako,
#                                             systemctl/dbus import-environment,
#                                             omarchy-first-run/powerprofiles)
#   EXCLUDED  ~/.config/hypr/autostart.conf  (steam, theme/power daemons)
#   EXCLUDED  ~/.config/hypr/monitors.conf   (host monitor layout; nested has
#                                             its own WAYLAND-1 + XR outputs)
#
# PRIVATE DBus session bus: preview-xr.sh launches this nested Hyprland under
# dbus-run-session, so the whole nested session (and every keybind-launched app,
# which inherits DBUS_SESSION_BUS_ADDRESS through Hyprland's fork/exec) has its OWN
# session bus. DBus/GApplication singletons (ghostty, walker, mako, browser,
# nautilus, obsidian, web-apps) therefore start FRESH nested instead of routing to
# their already-running HOST instances — the shared-bus delegation bug is gone, and
# no per-app single-instance override is needed. Side effects (all fine for a
# preview): nested notifications go to the nested mako (below), not the host;
# xdg-desktop-portal dbus-activates fresh on this bus (pickers/screencast may be
# limited); host DBus services (NetworkManager applet, etc.) are absent on the fresh
# bus. Anything that STILL routes to the host would only do so via a non-DBus channel
# (e.g. an X11/abstract-socket singleton) — none observed here.
#
# Per-session cosmetics (waybar, swaybg) plus mako are relaunched below via plain
# exec-once (mako is now safe: no org.freedesktop.Notifications clash on the private
# bus). hypridle/fcitx5/polkit stay OFF (global-state / unwanted in a preview).
# ==========================================================================

# Route keybind app-launches through the uwsm-app shim so they land in THIS
# nested session instead of the host session. Full literal PATH (hyprlang does
# not expand \$PATH in env values) with the shim dir first.
env = PATH,$PATH_LITERAL

# Nested output: one Wayland window on the host desktop (preview default; the
# host monitor layout in monitors.conf is intentionally NOT sourced).
monitor = , preferred, auto, 1

# ---- Look'n'feel / theme / input (Omarchy defaults + user overrides) ----
# Sourced live, so edits to these files show up on the next nested launch.
source = $OMARCHY_DEFAULT/envs.conf
source = $OMARCHY_DEFAULT/looknfeel.conf
source = $OMARCHY_DEFAULT/input.conf
source = $OMARCHY_DEFAULT/windows.conf
source = $THEME_DIR/hyprland.conf
source = $USER_HYPR/input.conf
source = $USER_HYPR/looknfeel.conf

# ---- Keybinds (Omarchy defaults + user) ----
source = $OMARCHY_DEFAULT/bindings/media.conf
source = $OMARCHY_DEFAULT/bindings/clipboard.conf
source = $USER_HYPR/bindings/tiling-v2.conf
source = $USER_HYPR/bindings/utilities.conf
source = $USER_HYPR/bindings.conf

# ---- Permanent config toggles (harmless flags) ----
source = $HOME_DIR/.local/state/omarchy/toggles/hypr/*.conf
CONF

# Terminal binds are left stock: the private DBus session bus (dbus-run-session in
# preview-xr.sh) means the default 'uwsm-app -- xdg-terminal-exec' bind opens a fresh
# nested terminal even for GApplication single-instance terminals like ghostty, so no
# per-terminal override is emitted anymore.

cat >> "$NESTED_CONF" <<CONF

# ---- Per-session cosmetics (SAFE: plain exec-once, no uwsm/systemd/dbus) ----
# waybar gives the Omarchy top bar; swaybg the themed wallpaper; mako the nested
# notification daemon. mako is safe here because the nested session has its OWN
# private DBus bus (dbus-run-session), so it owns org.freedesktop.Notifications on
# THAT bus with no clash against the host mako — nested notify-send now surfaces in
# the nested session. NOT launched: hypridle, fcitx5, polkit agent, or anything
# systemctl/dbus-* (global-state / unwanted in a preview).
exec-once = waybar
exec-once = swaybg -i $HOME_DIR/.config/omarchy/current/background -m fill
exec-once = mako

# ==========================================================================
# HypXRland XR essentials (equivalent of scripts/preview-xr.conf).
# preview-xr.sh appends openxr:gpu / openxr:overlay / openxr:blend_mode to the
# merged config on top of this file.
# ==========================================================================
openxr {
    enabled = 1
}

# A world-locked monitor straight ahead at eye height...
xrmonitor = XR-main, 1920x1080@60, anchor:local pos:0,1.5,-1.5 yaw:0, size:1.6
# ...and a head-leashed side panel that springs along with your view.
xrmonitor = XR-side, 1280x720@60, anchor:head offset:0.9,0,-1.2, size:0.9

# ---- XR keybinds (Omarchy 'bindd' style; arrow + SUPER+ALT keys are free) ----
# Lifecycle
bindd = SUPER ALT, C, Create XR monitor, xrmonitor, create XR-extra 1280x720 anchor:body offset:0,-0.3,-1.0
bindd = SUPER ALT, D, Destroy XR monitor, xrmonitor, destroy XR-extra
# Selection (which XR monitor the pose verbs act on)
bindd = SUPER ALT, N, Select next XR monitor, xrmonitor, select next
bindd = SUPER ALT, P, Select previous XR monitor, xrmonitor, select prev
# Pose: rotate / distance on the arrow keys (unbound in the Omarchy vim layout)
bindd = SUPER, LEFT, Rotate XR monitor left, xrmonitor, rotate -15
bindd = SUPER, RIGHT, Rotate XR monitor right, xrmonitor, rotate 15
bindd = SUPER, UP, Push XR monitor farther, xrmonitor, distance 0.25
bindd = SUPER, DOWN, Pull XR monitor closer, xrmonitor, distance -0.25
bindd = SUPER, HOME, Recenter XR monitor on gaze, xrmonitor, center
# Quit the nested compositor (SUPER+Q stays Omarchy's "close window").
bindd = SUPER SHIFT, Q, Exit nested session, exit
CONF

echo "generated:"
echo "  $NESTED_CONF"
echo "  $SHIM_DIR/uwsm-app  (uwsm-app shim)"
echo
echo "launch the nested Omarchy-mirror preview with:"
echo "  scripts/preview-xr.sh --conf $NESTED_CONF"
